INSERT INTO SECURITY_RESOURCE_GROUP (RESOURCE_GROUP_ID, RESOURCE_GROUP_NAME) VALUES (1,'global');
INSERT INTO SECURITY_RESOURCE_GROUP (RESOURCE_GROUP_ID, RESOURCE_GROUP_NAME) VALUES (2, 'resource_group_security');
INSERT INTO SECURITY_ROLE (ROLE_ID, ROLE_NAME) VALUES (1, 'security_root');
INSERT INTO SECURITY_USER (USER_ID, LOGIN_NAME, PASSWORD_VALUE, FIRST_NAME, LAST_NAME, locked, confirmed, access_counter, max_inactive_interval) VALUES (1, 'root', '{md5}Y6nw6nu5gFB5a2SehUgYRQ==', 'Super', 'User', false, true, 0, 0);
INSERT INTO SECURITY_USER (USER_ID, LOGIN_NAME, PASSWORD_VALUE, FIRST_NAME, LAST_NAME, locked, confirmed, access_counter, max_inactive_interval) VALUES (8, 'anonymous', 'x', 'Anonymous', 'User', false, true, 0, 0);
INSERT INTO SECURITY_USER_RESOURCE_GROUP_ROLE ( USER_ID, RESOURCE_GROUP_ID, ROLE_ID )
SELECT SECURITY_USER.USER_ID, SECURITY_RESOURCE_GROUP.RESOURCE_GROUP_ID, SECURITY_ROLE.ROLE_ID from 
SECURITY_USER, SECURITY_RESOURCE_GROUP, SECURITY_ROLE
WHERE SECURITY_USER.LOGIN_NAME = 'turbine' AND 
SECURITY_RESOURCE_GROUP.RESOURCE_GROUP_NAME = 'global' AND SECURITY_ROLE.ROLE_NAME = 'security_root';
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (1, 'security_change_password_u', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (2, 'security_change_own_password_u', 'Change user own password only. Allowed also for regular users'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (3, 'security_permission_c', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (4, 'security_permission_d', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (5, 'security_permission_r', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (6, 'security_permission_u', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (7, 'security_resource_group_c', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (8, 'security_resource_group_d', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (9, 'security_resource_group_r', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (10, 'security_resource_group_u', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (11, 'security_role_c', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (12, 'security_role_d', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (13, 'security_role_r', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (14, 'security_role_u', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (15, 'security_user_c', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (16, 'security_user_d', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (17, 'security_user_group_role_r', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (18, 'security_user_group_role_u', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (19, 'security_user_r', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (20, 'security_user_u', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (21, 'security_required_permission_r', 'Allows to view required permissions in grups for builers and actions'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (22, 'security_close_http_session', 'Allows to close other user http session. It causes of user logout'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (23, 'security_switch_user', 'Allows to switch to current httpSession to AccessControlList of another user'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (24, 'security_role_users_r', 'Read of users list who has given role'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (25, 'security_permission_users_r', 'Allows view of users, groups and roles where given permission is used'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (26, 'security_resource_group_users_r', 'Read of users who has in given group at least one permission'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (27, 'security_user_group_role_det_r', 'Detail user serurity group permission raport view'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (28, 'logged_in_users', 'Allows to view logged in user list'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (29, 'resource_reload', 'Resource reload permission: Security tokens, Secure menu, Templating subsystem'); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_PERMISSION (PERMISSION_ID, PERMISSION_NAME, PERMISSION_DESC)  VALUES  (30, '', ''); CALL NEXT VALUE FOR SECURITY_PERMISSION_SEQUENCE;
INSERT INTO SECURITY_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) 
SELECT SECURITY_ROLE.ROLE_ID, SECURITY_PERMISSION.PERMISSION_ID FROM 
SECURITY_ROLE, SECURITY_PERMISSION
WHERE SECURITY_PERMISSION.PERMISSION_NAME = 'admin_users' AND 
SECURITY_ROLE.ROLE_NAME = 'security_root';
